export const EnvEnum = {
  PORT: 'PORT',
  MONGO_URI: 'MONGO_URI',
  JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  JWT_REFRRESH_SECRET: 'JWT_REFRRESH_SECRET',
  JWT_ACCESS_DURATION: 'JWT_ACCESS_DURATION',
  JWT_REFRRESH_DURATION: 'JWT_REFRRESH_DURATION',
} as const;
